### ISSUE TITLE
SCRIPT_ADDRESS / PUBKEY_ADDRESS Details

### ISSUE THREAD

**Issue by daygle** [Crowndev/crown-core#101]
I am after help to find out the SCRIPT_ADDRESS and PUBKEY_ADDRESS decimal values for crown.

Is anyone able to provide me these details?

**Comment by FireWalkerX** [comment]
https://github.com/Crowndev/crown-core/blob/master/src/chainparams.cpp#L265 - here are the hex values - just use calculator for converting them to decimal

**Comment by daygle** [comment]
Thanks @FireWalkerX usually it's structured like (1,0) and (1,28).

I'm a little confused how to convert those values you mentioned. Are you able to provide pointers.

**Comment by FireWalkerX** [comment]
use windows calculator, choose programmer, thats where you can do it

**Comment by daygle** [comment]
Ended up figuring it out, closing.
