### ISSUE TITLE
Allow IPv6 - please read reasons

### ISSUE THREAD

**Issue by skironDotNet** [Crowndev/crown-core#127]
As the price of CRW is high and rewards low, it would make more sense to cut VPS cost by allowing IPv6, many VPS providers give /64 range for free so it would be possible to host multiple MNs at the cost of one VPS. I know I know centralization, but I do it anyway thanks to OVH one time fee for additional IP4.

Syscoin tried to solve this by not allowing multiple instances running, but this can be solved via separate user accounts, but I went beyond that and forked SYS and removed the protection, still need multiple IPv4, so I run CRW and SYS at same VPS. As for centralization, my servers run for 2 years with 0 downtime so far, except when I need to update software or DDoS brings MN down, but it has nothing to do with hosting in separate VPS vs in same.

**Comment by defunctec** [comment]
This should be closed since it's 3 years old, not an issue and more of a feature request and the project wouldn't have resource to implement anyway
