### ISSUE TITLE
Systemnode die unexpected

### ISSUE THREAD

**Issue by skironDotNet** [Crowndev/crown-core#91]
### Which version of Crown are you using? (QT or Daemon) Please include the version number.
latest

#### Use the debug.log in your data directory if possible. Running Crown with debug=1 in your crown.conf will provide even more information.

added: 

disablewallet=1
keypool=0

No errors in debug.log

linux: dmesg:

crown-legacysig[15831]: segfault at 108 ip 000000000069689c sp 00007ff2415b46b0 error 4 in crownd[400000+810000]

####
Any chance you can check running it with  disablewallet=1 
I think running MN/SN with wallet enabled just adds CPU load to scan addresses in the wallet...
Another solution to minimize CPU load would be to keep wallet enabled and set keypool=0 to have only 1 address in the wallet for scanning

**Comment by defunctec** [comment]
Is this still an issue with 0.13.4?
