### ISSUE TITLE
Please add option to disable logging to debug.log

### ISSUE THREAD

**Issue by skironDotNet** [Crowndev/crown-core#93]
Please add 

`fPrintToDebugLog=GetBoolArg("-printtodebug", true);`

Don't have to update documenation ie daemon help. But I don't think we need waste CPU and IO to write all those useless logs like InstantX::ProcessConsensusVote

 think even Bitcoin devs should add argument to disable all logging is someone wants... writing to /dev/null and other trick to prevent logging is still using CPU to process them in the daemon

**Comment by defunctec** [comment]
instantsend.log was introduced. Can be closed
