### ISSUE TITLE
0.13.2.0 getblocktemplate error 

### ISSUE THREAD

**Issue by kr1z1s** [Crowndev/crown-core#99]
```
crown-cli getblocktemplate
error: {"code":-7,"message":"Out of memory"}
```

**Comment by walkjivefly** [comment]
Why are you trying to call getblocktemplate? It's for use by miners with PoW coins. 
Crown is now exclusively PoS. Calling getblocktemplate makes no sense. 
The error could be improved, or better still the RPC simply removed.
But neither is likely to happen any time soon.

**Comment by kr1z1s** [comment]
> Why are you trying to call getblocktemplate? It's for use by miners with PoW coins.
> Crown is now exclusively PoS. Calling getblocktemplate makes no sense.
> The error could be improved, or better still the RPC simply removed.
> But neither is likely to happen any time soon.

Yes. You're right. I just tried calling RPC GBT and noticed the error
